apiVersion: apps/v1
kind: Deployment

metadata:
  name: springboot-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: springboot

  template:
    metadata:
      labels:
        app: springboot

    spec:
      containers:
      - name: springboot-container
        image: springboot-k8s-demo:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080